In [1]:
import numpy as np

def solve_linear_equation(A, b):
   # enter your code here, and remove the following line (30%)
   rank_A = np.linalg.matrix_rank(A)
   rank_A_b = np.linalg.matrix_rank(np.hstack((A, b)))

   if rank_A == rank_A_b:
     if rank_A == A.shape[1]:
       return 1
     else:
       return 0
   else:
     return -1

def flag_to_message(flag):
   if flag == 1:
     print('The linear system Ax=b has only one solution.')
   elif flag == 0:
     print('The linear system Ax=b has infinitely many solutions.')
   elif flag == -1:
     print('The linear system Ax=b has no solutions.')
   else:
     print('Unknown flag!')

def get_input_data(input_id):
   if input_id == 'case1': 
     A = np.array([[3, 2, -1], [6, -1, 3], [1, 10, -2]])
     b = np.array([[-7], [-4], [2]])
   elif input_id == 'case2':
     A = np.array([[4, -1, 3], [21, -4, 18], [-9, 1, -9]])
     b = np.array([[5], [7], [-8]])
   elif input_id == 'case3':
     A = np.array([[7, -4, 1], [3, 2, -1], [5, 12, -5]])
     b = np.array([[-15], [-5], [-5]])
   return A, b

if __name__ == '__main__':
   for case in ['case1', 'case2', 'case3']:
     A, b = get_input_data(case)
     print(case)
     print('A =', A, 'b =', b.T)
     flag = solve_linear_equation(A, b)
     flag_to_message(flag)
     if flag == 1:
       print('The solution is ', np.linalg.solve(A, b))
     print()


case1
A = [[ 3  2 -1]
 [ 6 -1  3]
 [ 1 10 -2]] b = [[-7 -4  2]]
The linear system Ax=b has only one solution.
The solution is  [[-2.]
 [ 1.]
 [ 3.]]

case2
A = [[ 4 -1  3]
 [21 -4 18]
 [-9  1 -9]] b = [[ 5  7 -8]]
The linear system Ax=b has no solutions.

case3
A = [[ 7 -4  1]
 [ 3  2 -1]
 [ 5 12 -5]] b = [[-15  -5  -5]]
The linear system Ax=b has infinitely many solutions.



In [2]:
# Can we use np.linalg.solve() to determine whether 𝐀𝐱=𝐛 is consistent? Explain the reason for your answer. (5%)
# Write down your answer here.

Ans: 不行，因為 np.linalg.solve() 只能解決 $A$ 為方陣的情況下，若 $A$ 不是方陣，則 np.linalg.solve() 會出現錯誤

In [3]:
# Given matrix 𝐀 of dimension (m,n). If rank(𝐀)=𝑛, can we infer that 𝐀𝐱=𝐛 is consistent? Explain the reason for your answer. (5%)
# Write down your answer here.

Ans: 不能，因為即便 rank($A$) = n ， 我們也不能確保 rank($A$) = rank([$A$   $b$]) (等價於這個線性系統 consistent)，也就是說 $Ax = b$ 有可能不存在解